#!/usr/bin/env bash
# =============================================================================
# update-wasm-checksums.sh — Regenerate reference WASM checksums
# =============================================================================
# Builds the fluxora_stream WASM artifact and updates wasm/checksums.sha256
# with the new SHA256 hash. Run this whenever the contract source changes
# and you want to update the canonical checksum that CI verifies against.
#
# Prerequisites:
#   - Rust toolchain with wasm32-unknown-unknown target
#   - cargo on PATH
#
# Usage:
#   bash script/update-wasm-checksums.sh
#
# After running, commit wasm/checksums.sha256 along with your source changes.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHECKSUM_FILE="${REPO_ROOT}/wasm/checksums.sha256"
WASM_PATH="target/wasm32-unknown-unknown/release/fluxora_stream.wasm"
PACKAGE_NAME="fluxora_stream"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

info "Building ${PACKAGE_NAME} (release / WASM)..."
cargo build --release -p "${PACKAGE_NAME}" --target wasm32-unknown-unknown 2>&1

FULL_WASM_PATH="${REPO_ROOT}/${WASM_PATH}"
[[ -f "${FULL_WASM_PATH}" ]] || error "WASM artifact not found at ${FULL_WASM_PATH} after build."

CHECKSUM=$(sha256sum "${FULL_WASM_PATH}" | awk '{print $1}')

info "WASM SHA256: ${CHECKSUM}"

# Write the checksums file
cat > "${CHECKSUM_FILE}" << EOF
# Fluxora Stream WASM Checksums
#
# This file contains reference SHA256 checksums for reproducible WASM builds.
# CI verifies that a fresh build produces byte-identical artifacts.
#
# Format: <sha256>  <filename>
# Generated by: script/update-wasm-checksums.sh
# Last updated: $(date -u +%Y-%m-%d)
#
# To regenerate, run: bash script/update-wasm-checksums.sh
#
# Determinism contract:
#   - Rust toolchain is pinned via rust-toolchain.toml (stable channel)
#   - soroban-sdk version is pinned in contracts/stream/Cargo.toml
#   - Build uses --release with wasm32-unknown-unknown target
#   - No environment-dependent flags or features beyond the pinned toolchain
#
${CHECKSUM}  fluxora_stream.wasm
EOF

success "Checksums written to ${CHECKSUM_FILE}"
echo ""
echo "Next steps:"
echo "  1. Review the change: cat ${CHECKSUM_FILE}"
echo "  2. Commit: git add wasm/checksums.sha256 && git commit -m 'chore: update wasm checksums'"
